# 去application.yml里配置active: test就可以运行本地test环境
server:
  port: 8081
  servlet:
    context-path: /diancan
spring:
  datasource:
    url: jdbc:mysql://124.222.48.147/diancan?characterEncoding=utf-8&useSSL=false&serverTimeZone=UTC
      &useOldAliasMetadataBehavior=true&allowPublicKeyRetrieval=true
    username: root
    password: xiong
    hikari:
      connection-init-sql: set names utf8mb4
    tomcat:
      init-s-q-l: SET NAMES utf8mb4 #这是最重要的一
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

